# dado = input('digite algo : ')
# print('O tipo primitivo desse valor é : ', type(dado))  
# print(' Só tem espaços?', dado.isspace())
# print('É um número?', dado.isnumeric())
# print('É alfabético?', dado.isalpha())
# print('É alfanumérico?', dado.isalnum())    
# print('Está em maiúsculas?', dado.isupper())
# print('Está em minúsculas?', dado.islower())
# print('Está capitalizada?', dado.istitle())  




# dado = input('digite algo: ')
# print(' o tipo de primitivo desse valor é : ', type(dado))
# print('é alfabeético?', dado.isalpha())
# print('é alfanumérico?', dado.isalnum())
# print('é numérico?', dado.isnumeric())
# print('está em maiúsculas?', dado.isupper())
# print('está em minúsculas?', dado.islower())
# print('está capitalizada?', dado.istitle())
# print('Só tem espaços?', dado.isspace())
# print('Só tem números?', dado.isnumeric())
# print('Só tem números e espaços?', dado.isspace() or dado.isnumeric())
# print('Só tem letras e espaços?', dado.isspace() or dado.isalpha())
# print('Só tem letras e números?', dado.isalnum() or dado.isalpha())


a = input('digite algo: ')
print(' otipo primitivo desse valor é :',type(a))

